swagger: '2.0'
info:
  version: '1.0.0'
  title: Parcel API
  description: An example API demonstrating protocol state dependencies
host: parcel.com
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
x-api-first-fsm-states:
  - packaged
  - in-transfer
  - destroyed
  - received
paths:
  /parcel/{id}:
    x-api-first-linked-data:
      - packaged:
          - self: '/parcel/{id}'
          - z.transfer: '/parcel/{id}/transfer'
      - in-transfer:
          - self: '/parcel/{id}'
          - z.transfer: '/parcel/{id}/transfer'
          - z.receipt: '/parcel/{id}/receipt'
      - destroyed:
          - self: '/parcel/{id}'
          - z.lost: '/parcel/{id}/lost'
      - received:
          - self: '/parcel/{id}'
          - z.receipt: '/parcel/{id}/receipt'
    post:
      x-api-first-fsm-transitions:
        - start: packaged
      description: creates a single parcel
      operationId: postParcel
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: parcel
          in: body
          required: true
          schema: 
            $ref: '#/definitions/parcel'
      responses:
        201:
          description: the created parcel
          schema:
            $ref: '#/definitions/parcel'
    put:
      x-api-first-fsm-transitions:
        - packaged: packaged
      description: updates a single parcel
      operationId: putParcel
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: parcel
          in: body
          required: true
          schema: 
            $ref: '#/definitions/parcel'
      responses:
        200:
          description: the updated parcel
          schema:
            $ref: '#/definitions/parcel'
    get:
      description: fetches a single parcel
      operationId: getParcel
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: the parcel
          schema:
            $ref: '#/definitions/parcel'
  /parcel/{id}/transfer:
    x-api-first-linked-data:
      - in-transfer:
          - self: '/parcel/{id}/transfer'
          - via: '/parcel/{id}'
          - z.receipt: '/parcel/{id}/receipt'
      - destroyed:
          - via: '/parcel/{id}'
          - z.lost: '/parcel/{id}/lost'
    post:
      x-fsm-transitions:
        - packaged: in-transfer
      operationId: postParcelTransfer
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: transfer
          in: body
          required: true
          schema: 
            $ref: '#/definitions/transfer'
      responses:
        201:
          description: the created parcel transfer
          schema:
            $ref: '#/definitions/transfer'
    put:
      x-api-first-fsm-transitions:
        - in-transfer: in-transfer
      description: updates a single parcel transfer
      operationId: putParcelTransfer
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: transfer
          in: body
          required: true
          schema: 
            $ref: '#/definitions/transfer'
      responses:
        200:
          description: parcel update
          schema:
            $ref: '#/definitions/parcel'
    get:
      x-api-first-fsm-transitions:
        - in-transfer: in-transfer
      description: fetches a single parcel transfer
      operationId: getParcelTransfer
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: the parcel transfer
          schema:
            $ref: '#/definitions/transfer'
    delete:
      x-api-first-fsm-transitions:
        - in-transfer: destroyed
      description: marks a parcel received
      operationId: deleteParcelTransfer
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: the parcel transfer
          schema:
            $ref: '#/definitions/transfer'
  /parcel/{id}/lost:
    x-api-first-linked-data:
      - destroyed:
          - self: '/parcel/{id}/lost'
          - via: '/parcel/{id}'
    get:
      x-api-first-fsm-transitions:
        - destroyed: destroyed
      description: fetches the information of a lost parcel
      operationId: getParcelLost
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: the lost parcel information
          schema:
            $ref: '#/definitions/lost'
  /parcel/{id}/receipt:
    x-api-first-linked-data:
      - received:
          - self: '/parcel/{id}/receipt'
          - via: '/parcel/{id}'
    post:
      x-api-first-fsm-transitions:
        - in-transfer: received
      description: creates a parcel received receipt
      operationId: postParcelReceivedReceipt
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: receipt
          in: body
          required: true
          schema: 
            $ref: '#/definitions/receipt'
      responses:
        200:
          description: the parcel received receipt
          schema:
            $ref: '#/definitions/receipt'
    get:
      x-api-first-fsm-transitions:
        - received: received
      description: fetches the information of a lost parcel
      operationId: getParcelLost
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: the parcel received receipt
          schema:
            $ref: '#/definitions/receipt'
definitions:
  parcel:
    required:
      - name
      - content
    properties:
      name:
        type: string
      content:
        type: array
        items:
          type: string
  transfer:
    required:
      - lon
      - lat
    properties:
      lon:
        type: number
        format: float
      lat:
        type: number
        format: float
  receipt:
    required:
      - recipient
    properties:
      recipient:
        type: string
      timestamp:
        type: string
        format: date-time
  lost:
    properties:
      timestamp:
        type: string
        format: date-time
